---
# tasks file for ansible-role-speedtest

- name: "Download Speedtest CLI install package locally"
  get_url:
    url: "https://install.speedtest.net/app/cli/ookla-speedtest-{{ version }}-linux-{{ ansible_facts['architecture'] }}.tgz"
    dest: "/tmp/ookla-speedtest-{{ version }}-linux-{{ ansible_facts['architecture'] }}.tgz"
    mode: '0644'
  delegate_to: 127.0.0.1

- name: "Copy the Speedtest CLI install package to {{ inventory_hostname }}"
  copy:
    src: "/tmp/ookla-speedtest-{{ version }}-linux-{{ ansible_facts['architecture'] }}.tgz"
    dest: /root/
    mode: '0644'

- name: "Extract the Speedtest CLI install package"
  shell: tar -xzf /tmp/ookla-speedtest-{{ version }}-linux-{{ ansible_facts['architecture'] }}.tgz --directory /bin --strip-components 1
  args:
    warn: false

- name: "Copy Speedtest CLI man page to correct location"
  copy:
    src: /bin/speedtest.5
    dest: /usr/share/man/man5/

- name: "Cleanup left-over files from Speedtest CLI install package"
  file:
    src: "{{ item }}"
    state: absent
  loop:
    - /bin/speedtest.5
    - /bin/speedtest.md
    - "/tmp/ookla-speedtest-{{ version }}-linux-{{ ansible_facts['architecture'] }}.tgz"
