---
# tasks file for ansible-role-speedtest

- name: "Include tasks from lookup playbook"
  include_tasks: lookup.yaml

- name: "Include tasks from install playbook"
  include_tasks: install.yaml
  when:
    - install is defined
    - install | bool
