---
# Speedtest tasks file for ansible-role-speedtest

- name: "Collect stats of Speedtest CLI executable"
  shell: speedtest --format=json-pretty
  register: output

- name: "Parse JSON from the stdout of output"
  set_fact:
    results: "{{ output.stdout | from_json }}"

- name: "Set Bandwidth facts"
  set_fact:
    download_mbps: "{{ (results.download.bandwidth * 8 / 1000000) | round(2) }}"
    upload_mbps: "{{ (results.upload.bandwidth * 8 / 1000000) | round(2) }}"
  when:
    - output.stdout != ''
