---
# Speedtest tasks file for ansible-role-speedtest

- name: "Collect stats of Speedtest CLI executable"
  shell: echo "yes" | speedtest --format=json-pretty
  register: output
  no_log: true

- name: "Parse JSON from the stdout of output"
  set_fact:
    results: "{{ output.stdout | from_json }}"
  no_log: true

- name: "Set Bandwidth facts"
  set_fact:
    download_mbps: "{{ (results.download.bandwidth * 8 / 1000000) | round(2) }}"
    upload_mbps: "{{ (results.upload.bandwidth * 8 / 1000000) | round(2) }}"
    isp: "{{ results.isp }}"
    external_ip: "{{ results.interface.externalIp }}"
  when:
    - output.stdout != ''
